
name: Ctrlr
options:
  minimumXcodeGenVersion: 2.37.0

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1"

targets:
  Ctrlr:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sinaudio.Ctrlr
      INFOPLIST_FILE: Sources/Info.plist
    sources:
      - path: Sources
    scheme:
      testTargets: []
